version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3005:3005
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - D:/aaadesktop/nestjs-course-code/mysql2-test:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - D:/aaadesktop/test-redis:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
